//variables
let btn = document.querySelector('#new-quote');
let quote = document.querySelector('.quote');
let person = document.querySelector('.person');
const quotes = [
    { quote: "The only limit to our realization of tomorrow will be our doubts of today.", person: "Franklin D. Roosevelt" },
    { quote: "Success is not in what you have, but who you are.", person: "Bo Bennett" },
    { quote: "Don't watch the clock; do what it does. Keep going.", person: "Sam Levenson" },
    { quote: "The future belongs to those who believe in the beauty of their dreams.", person: "Eleanor Roosevelt" },
    { quote: "Do not wait to strike till the iron is hot, but make it hot by striking.", person: "William Butler Yeats" },
    { quote: "Believe you can and you're halfway there.", person: "Theodore Roosevelt" },
    { quote: "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.", person: "Jordan Belfort" },
    { quote: "What you get by achieving your goals is not as important as what you become by achieving your goals.", person: "Zig Ziglar" },
    { quote: "It always seems impossible until it's done.", person: "Nelson Mandela" },
    { quote: "Strive not to be a success, but rather to be of value.", person: "Albert Einstein" },
    { quote: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", person: "Roy T. Bennett" },
    { quote: "The way to get started is to quit talking and begin doing.", person: "Walt Disney" },
    { quote: "I find that the harder I work, the more luck I seem to have.", person: "Thomas Jefferson" },
    { quote: "Success is stumbling from failure to failure with no loss of enthusiasm.", person: "Winston S. Churchill" },
    { quote: "The only place where success comes before work is in the dictionary.", person: "Vidal Sassoon" },
    { quote: "Success usually comes to those who are too busy to be looking for it.", person: "Henry David Thoreau" },
    { quote: "Don't be afraid to give up the good to go for the great.", person: "John D. Rockefeller" },
    { quote: "It is never too late to be what you might have been.", person: "George Eliot" },
    { quote: "You are never too old to set another goal or to dream a new dream.", person: "C.S. Lewis" },
    { quote: "The only way to do great work is to love what you do.", person: "Steve Jobs" },
    { quote: "Don't let the fear of losing be greater than the excitement of winning.", person: "Robert Kiyosaki" },
    { quote: "The best way to predict the future is to create it.", person: "Peter Drucker" },
    { quote: "I have not failed. I've just found 10,000 ways that won't work.", person: "Thomas A. Edison" },
    { quote: "It's not whether you get knocked down, it's whether you get up.", person: "Vince Lombardi" },
    { quote: "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", person: "Christian D. Larson" },
    { quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", person: "Ralph Waldo Emerson" },
    { quote: "You miss 100% of the shots you don't take.", person: "Wayne Gretzky" },
    { quote: "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.", person: "Vince Lombardi" },
    { quote: "The only person you are destined to become is the person you decide to be.", person: "Ralph Waldo Emerson" },
    { quote: "You can't go back and change the beginning, but you can start where you are and change the ending.", person: "C.S. Lewis" },
    { quote: "Success is not just about making money. It's about making a difference.", person: "Unknown" },
    { quote: "It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change.", person: "Charles Darwin" },
    { quote: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", person: "Roy T. Bennett" },
    { quote: "Do not wait to strike till the iron is hot, but make it hot by striking.", person: "William Butler Yeats" },
    { quote: "The only way to do great work is to love what you do.", person: "Steve Jobs" },
    { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", person: "Winston S. Churchill" },
    { quote: "Your time is limited, don't waste it living someone else's life.", person: "Steve Jobs" },
    { quote: "Skill is only developed by hours and hours of work.", person: "Usain Bolt" },
    { quote: "A little progress each day adds up to big results.", person: "Satya Nani" },
    { quote: "The best way to predict the future is to create it.", person: "Peter Drucker" },
    { quote: "The only limit to our realization of tomorrow will be our doubts of today.", person: "Franklin D. Roosevelt" },
    { quote: "Success is not in what you have, but who you are.", person: "Bo Bennett" },
    { quote: "Don't watch the clock; do what it does. Keep going.", person: "Sam Levenson" },
    { quote: "The future belongs to those who believe in the beauty of their dreams.", person: "Eleanor Roosevelt" },
    { quote: "Do not wait to strike till the iron is hot, but make it hot by striking.", person: "William Butler Yeats" },
    { quote: "Believe you can and you're halfway there.", person: "Theodore Roosevelt" },
    { quote: "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.", person: "Jordan Belfort" },
    { quote: "What you get by achieving your goals is not as important as what you become by achieving your goals.", person: "Zig Ziglar" },
    { quote: "It always seems impossible until it's done.", person: "Nelson Mandela" },
    { quote: "Strive not to be a success, but rather to be of value.", person: "Albert Einstein" },
    { quote: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", person: "Roy T. Bennett" },
    { quote: "The way to get started is to quit talking and begin doing.", person: "Walt Disney" },
    { quote: "I find that the harder I work, the more luck I seem to have.", person: "Thomas Jefferson" },
    { quote: "Success is stumbling from failure to failure with no loss of enthusiasm.", person: "Winston S. Churchill" },
    { quote: "The only place where success comes before work is in the dictionary.", person: "Vidal Sassoon" },
    { quote: "Success usually comes to those who are too busy to be looking for it.", person: "Henry David Thoreau" },
    { quote: "Don't be afraid to give up the good to go for the great.", person: "John D. Rockefeller" },
    { quote: "It is never too late to be what you might have been.", person: "George Eliot" },
    { quote: "You are never too old to set another goal or to dream a new dream.", person: "C.S. Lewis" },
    { quote: "The only way to do great work is to love what you do.", person: "Steve Jobs" },
    { quote: "Don't let the fear of losing be greater than the excitement of winning.", person: "Robert Kiyosaki" },
    { quote: "I have not failed. I've just found 10,000 ways that won't work.", person: "Thomas A. Edison" },
    { quote: "It's not whether you get knocked down, it's whether you get up.", person: "Vince Lombardi" },
    { quote: "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", person: "Christian D. Larson" },
    { quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", person: "Ralph Waldo Emerson" },
    { quote: "You miss 100% of the shots you don't take.", person: "Wayne Gretzky" },
    { quote: "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.", person: "Vince Lombardi" },
    { quote: "The only person you are destined to become is the person you decide to be.", person: "Ralph Waldo Emerson" },
    { quote: "You can't go back and change the beginning, but you can start where you are and change the ending.", person: "C.S. Lewis" },
    { quote: "Success is not just about making money. It's about making a difference.", person: "Unknown" },
    { quote: "It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change.", person: "Charles Darwin" },
    { quote: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", person: "Roy T. Bennett" },
    { quote: "Do not wait to strike till the iron is hot, but make it hot by striking.", person: "William Butler Yeats" },
    { quote: "The only way to do great work is to love what you do.", person: "Steve Jobs" },
    { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", person: "Winston S. Churchill" },
    { quote: "Your time is limited, don't waste it living someone else's life.", person: "Steve Jobs" },
    { quote: "Skill is only developed by hours and hours of work.", person: "Usain Bolt" },
    { quote: "A little progress each day adds up to big results.", person: "Satya Nani" },
    { quote: "The best way to predict the future is to create it.", person: "Peter Drucker" },
    { quote: "The only limit to our realization of tomorrow will be our doubts of today.", person: "Franklin D. Roosevelt" },
    { quote: "Success is not in what you have, but who you are.", person: "Bo Bennett" },
    { quote: "Don't watch the clock; do what it does. Keep going.", person: "Sam Levenson" },
    { quote: "The future belongs to those who believe in the beauty of their dreams.", person: "Eleanor Roosevelt" },
    { quote: "Do not wait to strike till the iron is hot, but make it hot by striking.", person: "William Butler Yeats" },
    { quote: "Believe you can and you're halfway there.", person: "Theodore Roosevelt" },
    { quote: "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.", person: "Jordan Belfort" },
    { quote: "What you get by achieving your goals is not as important as what you become by achieving your goals.", person: "Zig Ziglar" },
    { quote: "It always seems impossible until it's done.", person: "Nelson Mandela" },
    { quote: "Strive not to be a success, but rather to be of value.", person: "Albert Einstein" },
    { quote: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", person: "Roy T. Bennett" },
    { quote: "The way to get started is to quit talking and begin doing.", person: "Walt Disney" },
    { quote: "I find that the harder I work, the more luck I seem to have.", person: "Thomas Jefferson" },
    { quote: "Success is stumbling from failure to failure with no loss of enthusiasm.", person: "Winston S. Churchill" },
    { quote: "The only place where success comes before work is in the dictionary.", person: "Vidal Sassoon" },
    { quote: "Success usually comes to those who are too busy to be looking for it.", person: "Henry David Thoreau" },
    { quote: "Don't be afraid to give up the good to go for the great.", person: "John D. Rockefeller" },
    { quote: "It is never too late to be what you might have been.", person: "George Eliot" },
    { quote: "You are never too old to set another goal or to dream a new dream.", person: "C.S. Lewis" },
    { quote: "The only way to do great work is to love what you do.", person: "Steve Jobs" },
    { quote: "Don't let the fear of losing be greater than the excitement of winning.", person: "Robert Kiyosaki" },
    { quote: "The best way to predict the future is to create it.", person: "Peter Drucker" },
    { quote: "I have not failed. I've just found 10,000 ways that won't work.", person: "Thomas A. Edison" },
    { quote: "It's not whether you get knocked down, it's whether you get up.", person: "Vince Lombardi" },
    { quote: "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", person: "Christian D. Larson" },
    { quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", person: "Ralph Waldo Emerson" },
    { quote: "You miss 100% of the shots you don't take.", person: "Wayne Gretzky" },

];
btn.addEventListener('click' , function(){
    let random = Math.floor(Math.random() * quotes.length);
    quote.innerText = quotes[random].quote;
    person.innerText = quotes[random].person;
})